### ISSUE TITLE
You are amazing

### ISSUE THREAD

**Issue by monodop** [nitrix/dectalk#1]
Thank you for putting this together ❤️ 🙏

**Comment by nitrix** [comment]
You're welcome :)

The API is public and I run it purely for fun / personal use on a [Kubernetes cluster](https://github.com/nitrix/infrastructure/blob/master/nitrix.me/dectalk.yml) hosted in eastern Canada.
We use it on my friend's Discord server via a bot I made (see [Senko](https://github.com/nitrix/senko)) to get some laughs.

It's been popularized lately by games like [Moonbase Alpha](https://www.youtube.com/watch?v=1B488z1MmaA) and [Sanctum 2](https://www.youtube.com/watch?v=-DTRRw6DnZo) which comes with that TTS integrated.

If you have any suggestions on how to improve the API / web widget, let me know!

**Comment by monodop** [comment]
I had found the dectalk libraries and executable in another repo but spent days trying to get it running on a linux container. Once I found this repo I was able to see how you configured wine and called everything. I was missing a couple steps but the biggest thing was I didn't understand how to properly set up the Xvfb window. So now I have it fully integrated into my own discord bot and speaking properly!

https://github.com/monodop/DankDittiesBot

I see you also got voice commands and audio normalization working. I was able to get wit.ai and porcupine (wake word detection) working for voice commands, but I'm not a huge fan of sending all that data to facebook just to transcribe it. And for audio normalization I haven't started looking at that yet. Would love to know what you ended up using as your solution for those.

**Comment by nitrix** [comment]
**Privacy**

Mine uses porcupine and Google's speech-to-text cloud service, so we're in the same boat in terms of privacy concern.
At least, it only receives what it listens to between the moment the wake word is detected and some period of silence (or a maximum duration, whichever happens first), so that's slightly comforting.

**Porcupine wake words**

For Porcupine, you may want to know that the file that they train and let you download via their web console is only valid for 30-days. After that, the wake word stops working -- even though it's completely free and for personal use. I didn't want my bot to keep breaking on me so I patched the 1.7 binaries [here](https://github.com/nitrix/porcupine/tree/4dad7ca4269ffe9e4f7b76dd7fd3316f27fbc1f4/lib) so that it skips their check.

I'm thinking to do the same for 1.8 too, this way I can upgrade my project and also help others that are on 1.8 (the wake word files are version dependent).

**Audio normalization**

[I pipe the output of youtube-dl into ffmpeg](https://github.com/nitrix/senko/blob/661fc7eca4e9a6ad9764e36ce9daaec08ede8800/modules/deejay/deejay.go#L54-L89) to convert to PCM 16-bit signed audio (for discord). All I needed to do was put some additional flags on that ffmpeg process: `-filter:a loudnorm`. It's a built-in filter that will make things louder or quieter to stay around the same loudness.

It's not prefect. You can sometime notice it adjust during a song. Like, if a singer stops singing, the background music will take over louder, but I don't mind too much. It saved my ears multiple times from ear rape.

**Contact**

nitrix on Freenode and nitrix#6946 on Discord.
